# Projeto 6 - Construindo e Operacionalizando Pipeline de Previs√£o em Tempo Real

services:
  app:
    build: .
    container_name: mlopsprojeto6
    ports:
      - "8000:8000"
    volumes:
      - ./modelo:/app/modelo
      - ./dados:/app/dados
    restart: always
